"""
Backwards-compatibility shim.

This module re-exports everything from
`ironframe.compliance.adapters.finra_v1_0` so that existing code using
the old import path continues to work:

    from ironframe.compliance.finra_v1_0 import ...   # still works
    from ironframe.compliance.adapters.finra_v1_0 import ...   # preferred

DO NOT EDIT THIS FILE. It is generated by sync_to_pure.py.
The authoritative source is ironframe/compliance/adapters/finra_v1_0.py.
"""

from ironframe.compliance.adapters.finra_v1_0 import *  # noqa: F401,F403
from ironframe.compliance.adapters import finra_v1_0 as _impl

# Re-export module-level attributes for star-import consumers
_module_globals = globals()
for _name in dir(_impl):
    if not _name.startswith("_"):
        _module_globals[_name] = getattr(_impl, _name)
